refresh:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: be_gas_prices
backfill_statistics:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: be_gas_prices
    start_date:
      required: false
      selector:
        date:
    clear:
      required: false
      default: false
      selector:
        boolean:
